apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- config/
- browser.Certificate.yaml
- browser.Deployment.yaml
- browser.Ingress.yaml
- browser.Service.yaml
- buildbarn.Namespace.yaml
- frontend.Certificate.yaml
- frontend.Deployment.yaml
- frontend.Ingress.yaml
- frontend.Service.yaml
- scheduler.Certificate.yaml
- scheduler.Deployment.yaml
- scheduler.Ingress.yaml
- scheduler.Service.yaml
- storage.Service.yaml
- storage.StatefulSet.yaml
- worker-starterkit-ash-coreutils-x86_64-cc.Deployment.yaml
- worker-starterkit-ash.Deployment.yaml
- worker-starterkit-ash-x86_64-cc.Deployment.yaml
- worker-starterkit-bash-coreutils-x86_64-cc.Deployment.yaml
- worker-ubuntu22-04.Deployment.yaml
